language: objective-c
sudo: enabled
os: osx
osx_image: xcode9.3

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: stable

before_install:
  - brew update # see note below
  - brew install node
  - brew install mozilla-addon-sdk
  - npm i -g jpm
